pub mod ansi;
pub mod columns;
pub mod badge;
pub mod frame;
pub mod table;
pub mod cursor;
pub mod list;
pub mod elapsed;
pub mod error;
pub mod log;
pub mod progress_bar;
pub mod spinner;
pub mod style;
pub mod text;
pub mod timer;
pub mod unicode;
pub mod writer;

pub use error::{PrismError, PrismResult};
pub use style::{s, style, color, rgb, hex, Color, Style, RESET};
pub use writer::{is_tty, interactive_tty, ansi_enabled, term_width};
